// src/utils/surahData.js
// Each entry: { n, ar, en, juz, page }
// juz  = which juz the surah starts in
// page = approximate page within that juz (Madani Mushaf / standard 15-line PDF)
// Fine-tune page values to match your specific PDF files if needed.

export const SURAHS = [
  { n:   1, ar: "الفاتحة",    en: "Al-Fatihah",     juz:  1, page:  4 },
  { n:   2, ar: "البقرة",     en: "Al-Baqarah",     juz:  1, page:  5 },
  { n:   3, ar: "آل عمران",   en: "Ali 'Imran",     juz:  3, page:  12 },
  { n:   4, ar: "النساء",     en: "An-Nisa",        juz:  4, page:  22 },
  { n:   5, ar: "المائدة",    en: "Al-Ma'idah",     juz:  6, page:  7 },
  { n:   6, ar: "الأنعام",    en: "Al-An'am",       juz:  7, page:  9 },
  { n:   7, ar: "الأعراف",    en: "Al-A'raf",       juz:  8, page:  13 },
  { n:   8, ar: "الأنفال",    en: "Al-Anfal",       juz:  9, page: 22 },
  { n:   9, ar: "التوبة",     en: "At-Tawbah",      juz: 10, page:  8 },
  { n:  10, ar: "يونس",       en: "Yunus",          juz: 11, page:  8 },
  { n:  11, ar: "هود",        en: "Hud",            juz: 11, page: 28 },
  { n:  12, ar: "يوسف",       en: "Yusuf",          juz: 12, page: 20 },
  { n:  13, ar: "الرعد",      en: "Ar-Ra'd",        juz: 13, page:  10 },
  { n:  14, ar: "إبراهيم",    en: "Ibrahim",        juz: 13, page: 19 },
  { n:  15, ar: "الحجر",      en: "Al-Hijr",        juz: 13, page:  28 },
  { n:  16, ar: "النحل",      en: "An-Nahl",        juz: 14, page:  8 },
  { n:  17, ar: "الإسراء",    en: "Al-Isra",        juz: 15, page:  1 },
  { n:  18, ar: "الكهف",      en: "Al-Kahf",        juz: 15, page: 16 },
  { n:  19, ar: "مريم",       en: "Maryam",         juz: 16, page:  5 },
  { n:  20, ar: "طه",         en: "Ta-Ha",          juz: 16, page: 15 },
  { n:  21, ar: "الأنبياء",   en: "Al-Anbiya",      juz: 17, page:  1 },
  { n:  22, ar: "الحج",       en: "Al-Hajj",        juz: 17, page: 14 },
  { n:  23, ar: "المؤمنون",   en: "Al-Mu'minun",    juz: 18, page:  1 },
  { n:  24, ar: "النور",      en: "An-Nur",         juz: 18, page: 11 },
  { n:  25, ar: "الفرقان",    en: "Al-Furqan",      juz: 18, page: 25 },
  { n:  26, ar: "الشعراء",    en: "Ash-Shu'ara",    juz: 19, page:  7 },
  { n:  27, ar: "النمل",      en: "An-Naml",        juz: 19, page: 21 },
  { n:  28, ar: "القصص",      en: "Al-Qasas",       juz: 20, page:  5 },
  { n:  29, ar: "العنكبوت",   en: "Al-'Ankabut",    juz: 20, page: 20 },
  { n:  30, ar: "الروم",      en: "Ar-Rum",         juz: 21, page:  4 },
  { n:  31, ar: "لقمان",      en: "Luqman",         juz: 21, page: 13 },
  { n:  32, ar: "السجدة",     en: "As-Sajdah",      juz: 21, page: 19 },
  { n:  33, ar: "الأحزاب",    en: "Al-Ahzab",       juz: 21, page: 23 },
  { n:  34, ar: "سبأ",        en: "Saba",           juz: 22, page:  9 },
  { n:  35, ar: "فاطر",       en: "Fatir",          juz: 22, page: 17 },
  { n:  36, ar: "يس",         en: "Ya-Sin",         juz: 22, page: 25 },
  { n:  37, ar: "الصافات",    en: "As-Saffat",      juz: 23, page:  6 },
  { n:  38, ar: "ص",          en: "Sad",            juz: 23, page: 16 },
  { n:  39, ar: "الزمر",      en: "Az-Zumar",       juz: 23, page: 23 },
  { n:  40, ar: "غافر",       en: "Ghafir",         juz: 24, page:  7 },
  { n:  41, ar: "فصلت",       en: "Fussilat",       juz: 24, page: 19 },
  { n:  42, ar: "الشورى",     en: "Ash-Shura",      juz: 25, page:  2 },
  { n:  43, ar: "الزخرف",     en: "Az-Zukhruf",     juz: 25, page: 11 },
  { n:  44, ar: "الدخان",     en: "Ad-Dukhan",      juz: 25, page: 20 },
  { n:  45, ar: "الجاثية",    en: "Al-Jathiyah",    juz: 25, page: 25 },
  { n:  46, ar: "الأحقاف",    en: "Al-Ahqaf",       juz: 26, page:  1 },
  { n:  47, ar: "محمد",       en: "Muhammad",       juz: 26, page:  8 },
  { n:  48, ar: "الفتح",      en: "Al-Fath",        juz: 26, page: 14 },
  { n:  49, ar: "الحجرات",    en: "Al-Hujurat",     juz: 26, page: 20 },
  { n:  50, ar: "ق",          en: "Qaf",            juz: 26, page: 25 },
  { n:  51, ar: "الذاريات",   en: "Adh-Dhariyat",   juz: 26, page: 29 },
  { n:  52, ar: "الطور",      en: "At-Tur",         juz: 27, page:  3 },
  { n:  53, ar: "النجم",      en: "An-Najm",        juz: 27, page:  6 },
  { n:  54, ar: "القمر",      en: "Al-Qamar",       juz: 27, page:  10 },
  { n:  55, ar: "الرحمن",     en: "Ar-Rahman",      juz: 27, page: 14 },
  { n:  56, ar: "الواقعة",    en: "Al-Waqi'ah",     juz: 27, page: 19 },
  { n:  57, ar: "الحديد",     en: "Al-Hadid",       juz: 27, page: 24 },
  { n:  58, ar: "المجادلة",   en: "Al-Mujadila",    juz: 28, page:  1 },
  { n:  59, ar: "الحشر",      en: "Al-Hashr",       juz: 28, page:  5 },
  { n:  60, ar: "الممتحنة",   en: "Al-Mumtahanah",  juz: 28, page: 10 },
  { n:  61, ar: "الصف",       en: "As-Saf",         juz: 28, page: 14 },
  { n:  62, ar: "الجمعة",     en: "Al-Jumu'ah",     juz: 28, page: 17 },
  { n:  63, ar: "المنافقون",  en: "Al-Munafiqun",   juz: 28, page: 19 },
  { n:  64, ar: "التغابن",    en: "At-Taghabun",    juz: 28, page: 21 },
  { n:  65, ar: "الطلاق",     en: "At-Talaq",       juz: 28, page: 24 },
  { n:  66, ar: "التحريم",    en: "At-Tahrim",      juz: 28, page: 27 },
  { n:  67, ar: "الملك",      en: "Al-Mulk",        juz: 29, page:  1 },
  { n:  68, ar: "القلم",      en: "Al-Qalam",       juz: 29, page:  4 },
  { n:  69, ar: "الحاقة",     en: "Al-Haqqah",      juz: 29, page:  8 },
  { n:  70, ar: "المعارج",    en: "Al-Ma'arij",     juz: 29, page: 11 },
  { n:  71, ar: "نوح",        en: "Nuh",            juz: 29, page: 14 },
  { n:  72, ar: "الجن",       en: "Al-Jinn",        juz: 29, page: 17 },
  { n:  73, ar: "المزمل",     en: "Al-Muzzammil",   juz: 29, page: 20 },
  { n:  74, ar: "المدثر",     en: "Al-Muddathir",   juz: 29, page: 22 },
  { n:  75, ar: "القيامة",    en: "Al-Qiyamah",     juz: 29, page: 25 },
  { n:  76, ar: "الإنسان",    en: "Al-Insan",       juz: 29, page: 27 },
  { n:  77, ar: "المرسلات",   en: "Al-Mursalat",    juz: 29, page: 30 },
  { n:  78, ar: "النبأ",      en: "An-Naba",        juz: 30, page:  1 },
  { n:  79, ar: "النازعات",   en: "An-Nazi'at",     juz: 30, page:  2 },
  { n:  80, ar: "عبس",        en: "'Abasa",         juz: 30, page:  4 },
  { n:  81, ar: "التكوير",    en: "At-Takwir",      juz: 30, page:  6 },
  { n:  82, ar: "الانفطار",   en: "Al-Infitar",     juz: 30, page:  7 },
  { n:  83, ar: "المطففين",   en: "Al-Mutaffifin",  juz: 30, page:  8 },
  { n:  84, ar: "الانشقاق",   en: "Al-Inshiqaq",    juz: 30, page:  10 },
  { n:  85, ar: "البروج",     en: "Al-Buruj",       juz: 30, page:  11 },
  { n:  86, ar: "الطارق",     en: "At-Tariq",       juz: 30, page: 12 },
  { n:  87, ar: "الأعلى",     en: "Al-A'la",        juz: 30, page: 13 },
  { n:  88, ar: "الغاشية",    en: "Al-Ghashiyah",   juz: 30, page: 14 },
  { n:  89, ar: "الفجر",      en: "Al-Fajr",        juz: 30, page: 15 },
  { n:  90, ar: "البلد",      en: "Al-Balad",       juz: 30, page: 17 },
  { n:  91, ar: "الشمس",      en: "Ash-Shams",      juz: 30, page: 18 },
  { n:  92, ar: "الليل",      en: "Al-Layl",        juz: 30, page: 19 },
  { n:  93, ar: "الضحى",      en: "Ad-Duha",        juz: 30, page: 20 },
  { n:  94, ar: "الشرح",      en: "Ash-Sharh",      juz: 30, page: 20 },
  { n:  95, ar: "التين",      en: "At-Tin",         juz: 30, page: 21 },
  { n:  96, ar: "العلق",      en: "Al-'Alaq",       juz: 30, page: 21 },
  { n:  97, ar: "القدر",      en: "Al-Qadr",        juz: 30, page: 22 },
  { n:  98, ar: "البينة",     en: "Al-Bayyinah",    juz: 30, page: 22 },
  { n:  99, ar: "الزلزلة",    en: "Az-Zalzalah",    juz: 30, page: 23 },
  { n: 100, ar: "العاديات",   en: "Al-'Adiyat",     juz: 30, page: 24 },
  { n: 101, ar: "القارعة",    en: "Al-Qari'ah",     juz: 30, page: 25 },
  { n: 102, ar: "التكاثر",    en: "At-Takathur",    juz: 30, page: 25 },
  { n: 103, ar: "العصر",      en: "Al-'Asr",        juz: 30, page: 26 },
  { n: 104, ar: "الهمزة",     en: "Al-Humazah",     juz: 30, page: 26 },
  { n: 105, ar: "الفيل",      en: "Al-Fil",         juz: 30, page: 26 },
  { n: 106, ar: "قريش",       en: "Quraysh",        juz: 30, page: 27 },
  { n: 107, ar: "الماعون",    en: "Al-Ma'un",       juz: 30, page: 27 },
  { n: 108, ar: "الكوثر",     en: "Al-Kawthar",     juz: 30, page: 28 },
  { n: 109, ar: "الكافرون",   en: "Al-Kafirun",     juz: 30, page: 28 },
  { n: 110, ar: "النصر",      en: "An-Nasr",        juz: 30, page: 28 },
  { n: 111, ar: "المسد",      en: "Al-Masad",       juz: 30, page: 29 },
  { n: 112, ar: "الإخلاص",    en: "Al-Ikhlas",      juz: 30, page: 29 },
  { n: 113, ar: "الفلق",      en: "Al-Falaq",       juz: 30, page: 29 },
  { n: 114, ar: "الناس",      en: "An-Nas",         juz: 30, page: 30 },
];

// Quick lookup by surah number
export const SURAH_MAP = Object.fromEntries(SURAHS.map((s) => [s.n, s]));

// All surahs that start in a given juz
export function surahsInJuz(juz) {
  return SURAHS.filter((s) => s.juz === juz);
}